//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo : Tagueado
    {
        public string Placa { get; set; }
        public string Selo { get; set; }
        public string Motorista { get; set; }
        public string Cor { get; set; }
        public string Patente { get; set; }
        public string Setor { get; set; }
        public string Modelo { get; set; }
    }
}
