//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitante : Tagueado
    {
        public string Identificacao { get; set; }
        public string Leito { get; set; }
        public string Nome { get; set; }
        public string Tipo { get; set; }
    }
}
