// <auto-generated />
namespace Cruzeiro.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_db));
        
        string IMigrationMetadata.Id
        {
            get { return "201605310132485_create_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
