//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cruzeiro.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cruzeiro.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo Letivo	Ano de Aluno	Estrutura da Organização	Curso	Turma Base do Aluno	Matrícula do Aluno	Nome do Aluno
        ///2016	2014	COLÉGIO CRUZEIRO - CENTRO	1º ANO ENSINO FUNDAMENTAL I	10011	14010006	ANA BEATRIZ DIAS NOVAES
        ///2016	2015	COLÉGIO CRUZEIRO - CENTRO	1º ANO ENSINO FUNDAMENTAL I	10011	15010597	BERNARDO MEDEIROS PEYNEAU GOMES
        ///2016	2014	COLÉGIO CRUZEIRO - CENTRO	1º ANO ENSINO FUNDAMENTAL I	10011	14010130	CATARINA DUARTE PINTO JEUNON VARGAS
        ///2016	2014	COLÉGIO CRUZEIRO - CENTRO	1º ANO ENSINO FUNDAMENTAL I	10011 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Exportar_Dados {
            get {
                return ResourceManager.GetString("Exportar_Dados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000002	ANGELINA DA SILVA BRIGADA	PROFESSOR
        ///00000004	ARLETE PILOSSOF VERA	PROFESSOR
        ///00000005	NEUZA MARIA BIDOIA DE OLIVEIRA	FUNCIONARIO
        ///00000011	JOSE GUILHERME DA SILVA	PROFESSOR
        ///00000012	INGRID LIPKE PREUSS	PROFESSOR
        ///00000017	TANIA GOMES PEREIRA	FUNCIONARIO
        ///00000018	CLESIO MORAES DOS SANTOS	FUNCIONARIO
        ///00000019	NECY DA COSTA NUNES	FUNCIONARIO
        ///00000021	ARLETI DA PENHA ROCHA	FUNCIONARIO
        ///00000023	MARLENE CAMPOS NOGUEIRA	PROFESSOR
        ///00000048	CARMEM RUTH M DUARTE	PROFESSOR
        ///00000049	ELISABETE MARIA DA  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Importação_de_Funcionários {
            get {
                return ResourceManager.GetString("Importação_de_Funcionários", resourceCulture);
            }
        }
    }
}
